extends: standard
parser: babel-eslint
parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
      impliedStrict: true
      jsx: true
rules:
  react/jsx-no-undef: 0
  react/no-did-mount-set-state: 0
  react/prefer-stateless-function: 0
  react/prop-types: 0
  react/jsx-uses-vars: 1
  react/jsx-uses-react: 1
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  no-undef: 0
plugins:
  - react